on:
  push:
    branches:
      - dev
      - next
      - feature/*
      - bugfix/*
      - main
  pull_request:
    branches:
      - main

name: run tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest] #, macos-latest, windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Setup laraboot CLI
        uses: laraboot-io/github-actions/setup-cli@cli-actions
      - uses: buildpacks/github-actions/setup-pack@v4.1.0
        with:
          pack-version: 0.20.0
      - name: Gh action
        uses: laraboot-io/laraboot-commander/actions/commander@gh-action
        with:
          name: my-buildpack
          version: 0.0.2
          file: commander.example.yml
      - name: Integration test
        run: make tests